# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors: 
  docker:
    docker:
      - image: cimg/node:stable
    parallelism: 4

orbs:
  node: circleci/node@4.7

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string

    executor: << parameters.os >>

    working_directory: ~/live

    steps:
      - checkout

      - persist_to_workspace:
          root: .
          paths: ./*

      - run: npm run eslint-report

      - store_test_results:
          path: ./reports/eslint.xml

      - store_artifacts:
          path: ./reports/eslint.xml

      - run:
          command: npm run mocha-report
          environment:
            MOCHA_FILE: ./reports/mocha.xml
          when: always

      - store_test_results:
          path: ./reports/mocha.xml

      - store_artifacts:
          path: ./reports/mocha.xml

      - run: npm audit

workflows:
  version: 2

  all:
    jobs:
      - test:
          matrix:
            parameters:
              os: ["docker"]
              node-version: ["10", "12", "14", "16"]